export enum Application {
  GET_APPLICATION_CALLER = 'GET_APPLICATION_CALLER',
  GET_APPLICATION_STARTER = 'GET_APPLICATION_STARTER',
  GET_APPLICATION_SUCCESS = 'GET_APPLICATION_SUCCESS',
  GET_APPLICATION_FAILURE = 'GET_APPLICATION_FAILURE',
  GET_APPLICATION_DEFAULT = 'GET_APPLICATION_DEFAULT',
}

export enum ValueSetters {
  SET_APPLICATION_TO_VIEW_CALLER = 'SET_APPLICATION_TO_VIEW_CALLER',
  SET_APPLICATION_TO_VIEW = 'SET_APPLICATION_TO_VIEW',
}

export enum DeclineMessageSetter {
  SET_DECLINE_MESSAGE = 'SET_DECLINE_MESSAGE',
}

export enum AcceptedApplicationActions {
  APPLICATION_ACCEPTED_CALLER = 'APPLICATION_ACCEPTED_CALLER',
  APPLICATION_ACCEPTED_STARTED = 'APPLICATION_ACCEPTED_STARTED',
  APPLICATION_ACCEPTED_SUCCESS = 'APPLICATION_ACCEPTED_SUCCESS',
  APPLICATION_ACCEPTED_FAILED = 'APPLICATION_ACCEPTED_FAILED',
  APPLICATION_ACCEPTED_DEFAULT = 'APPLICATION_ACCEPTED_DEFAULT',
}

export enum DeclinedApplicationActions {
  APPLICATION_DECLINED_CALLER = 'APPLICATION_DECLINED_CALLER',
  APPLICATION_DECLINED_STARTED = 'APPLICATION_DECLINED_STARTED',
  APPLICATION_DECLINED_SUCCESS = 'APPLICATION_DECLINED_SUCCESS',
  APPLICATION_DECLINED_FAILED = 'APPLICATION_DECLINED_FAILED',
  APPLICATION_DECLINED_DEFAULT = 'APPLICATION_DECLINED_DEFAULT',
}
