export enum getEnvironmentConfigs {
  GET_EVN_CONFIGS_CALLER = 'GET_EVN_CONFIGS_CALLER',
  GET_EVN_CONFIGS_STARTED = 'GET_EVN_CONFIGS_STARTED',
  GET_EVN_CONFIGS_SUCCESS = 'GET_EVN_CONFIGS_SUCCESS',
  GET_EVN_CONFIGS_FAILED = 'GET_EVN_CONFIGS_FAILED',
  GET_EVN_CONFIGS_DEFAULT = 'GET_EVN_CONFIGS_DEFAULT',
}

export enum setEnvironmentConfigs {
  SET_ENV_CONFIGS_CALLER = 'SET_ENV_CONFIGS_CALLER',
  SET_ENV_CONFIGS_STARTED = 'SET_ENV_CONFIGS_STARTED',
  SET_ENV_CONFIGS_SUCCESS = 'SET_ENV_CONFIGS_SUCCESS',
  SET_ENV_CONFIGS_FAILED = 'SET_ENV_CONFIGS_FAILED',
  SET_ENV_CONFIGS_DEFAULT = 'SET_ENV_CONFIGS_DEFAULT',
}

export enum setEnvironmentConfigsInput {
  SET_ENV_CONFIGS_INPUT_CALLER = 'SET_ENV_CONFIGS_INPUT_CALLER',
  SET_ENV_CONFIGS_INPUT = 'SET_ENV_CONFIGS',
}
