export enum GetCvActions {
  GET_CV_CALLER = "GET_CV_CALLER",
  GET_CV_STARTED = "GET_CV_STARTED",
  GET_CV_FAILED = "GET_CV_FAILED",
  GET_CV_SUCCESS = "GET_CV_SUCCESS",
  GET_CV_DEFAULT = "GET_CV_DEFAULT",
}

export enum AddCredentialsAction {
  ADD_CREDENTIALS_CALLER = "ADD_CREDENTIALS_CALLER",
  ADD_CREDENTIALS_STARTED = "ADD_CREDENTIALS_STARTED",
  ADD_CREDENTIALS_DEFAULT = "ADD_CREDENTIALS_DEFAULT",
  ADD_CREDENTIALS_FAILED = "ADD_CREDENTIALS_FAILED",
  ADD_CREDENTIALS_SUCCESS = "ADD_CREDENTIALS_SUCCESS",
}

export enum DeleteCredentialAction {
  DELETE_CREDENTIALS_CALLER = "DELETE_CREDENTIALS_CALLER",
  DELETE_CREDENTIALS_STARTED = "DELETE_CREDENTIALS_STARTED",
  DELETE_CREDENTIALS_DEFAULT = "DELETE_CREDENTIALS_DEFAULT",
  DELETE_CREDENTIALS_FAILED = "DELETE_CREDENTIALS_FAILED",
  DELETE_CREDENTIALS_SUCCESS = "DELETE_CREDENTIALS_SUCCESS",
}
