export enum GetAdminAccount {
  GET_ADMINS_STARTED = "GET_ADMINS_STARTED",
  GET_ADMINS_CALLER = "GET_ADMINS_CALLER",
  GET_ADMINS_DEFAULT = "GET_ADMINS_DEFAULT",
  GET_ADMINS_FAILED = "GET_ADMINS_FAILED",
  GET_ADMINS_SUCCESS = "GET_ADMINS_SUCCESS",
}

export enum ValueSetters {
  //CALLERS
  SET_ADMIN_TO_VIEW_CALLER = "SET_ADMIN_TO_VIEW_CALLER",

  // SETTERS
  SET_ADMIN_TO_VIEW = "SET_ADMIN_TO_VIEW",
}

export enum AdminSearchData {
  GET_ADMIN_SEARCH_RESULT_CALLER = "GET_ADMIN_SEARCH_RESULT_CALLER",
  GET_ADMIN_SEARCH_RESULT_STARTED = "GET_ADMIN_SEARCH_RESULT_STARTED",
  GET_ADMIN_SEARCH_RESULT_SUCCESS = "GET_ADMIN_SEARCH_RESULT_SUCCESS",
  GET_ADMIN_SEARCH_RESULT_FAILED = "GET_ADMIN_SEARCH_RESULT_FAILED",
  GET_ADMIN_SEARCH_RESULT_DEFAULT = "GET_ADMIN_SEARCH_RESULT_DEFAULT",
}

export enum RemoveAdminAccount {
  REMOVE_ADMIN_ACCOUNT_MANAGER_CALLER = "REMOVE_ADMIN_ACCOUNT_MANAGER_CALLER",
  REMOVE_ADMIN_ACCOUNT_MANAGER_STARTED = "REMOVE_ADMIN_ACCOUNT_MANAGER_STARTED",
  REMOVE_ADMIN_ACCOUNT_MANAGER_SUCCESS = "REMOVE_ADMIN_ACCOUNT_MANAGER_SUCCESS",
  REMOVE_ADMIN_ACCOUNT_MANAGER_FAILED = "REMOVE_ADMIN_ACCOUNT_MANAGER_FAILED",
  REMOVE_ADMIN_ACCOUNT_MANAGER_DEFAULT = "REMOVE_ADMIN_ACCOUNT_MANAGER_DEFAULT",
}

export enum UpdateAdminAccount {
  UPDATE__ADMIN_ACCOUNT_MANAGER_CALLER = "UPDATE__ADMIN_ACCOUNT_MANAGER_CALLER",
  UPDATE__ADMIN_ACCOUNT_MANAGER_STARTED = "UPDATE__ADMIN_ACCOUNT_MANAGER_STARTED",
  UPDATE__ADMIN_ACCOUNT_MANAGER_SUCCESS = "UPDATE__ADMIN_ACCOUNT_MANAGER_SUCCESS",
  UPDATE__ADMIN_ACCOUNT_MANAGER_FAILED = "UPDATE__ADMIN_ACCOUNT_MANAGER_FAILED",
  UPDATE__ADMIN_ACCOUNT_MANAGER_DEFAULT = "UPDATE__ADMIN_ACCOUNT_MANAGER_DEFAULT",
}

export enum AddAdminAccount {
  ADD_ADMIN_ACCOUNT_MANAGER_CALLER = "ADD_ADMIN_ACCOUNT_MANAGER_CALLER",
  ADD_ADMIN_ACCOUNT_MANAGER_STARTED = "ADD_ADMIN_ACCOUNT_MANAGER_STARTED",
  ADD_ADMIN_ACCOUNT_MANAGER_SUCCESS = "ADD_ADMIN_ACCOUNT_MANAGER_SUCCESS",
  ADD_ADMIN_ACCOUNT_MANAGER_FAILED = "ADD_ADMIN_ACCOUNT_MANAGER_FAILED",
  ADD_ADMIN_ACCOUNT_MANAGER_DEFAULT = "ADD_ADMIN_ACCOUNT_MANAGER_DEFAULT",
}
