export enum Driver {
  GET_DRIVER_CALLER = "GET_DRIVER_CALLER",
  GET_DRIVER_STARTER = "GET_DRIVER_STARTED",
  GET_DRIVER_SUCCESS = "GET_DRIVER_SUCCESS",
  GET_DRIVER_FAILED = "GET_DRIVER_FAILED",
  GET_DRIVER_DEFAULT = "GET_DRIVER_DEFAULT",
}

export enum ValueSetters {
  SET_DRIVER_TO_VIEW_CALLER = "SET_DRIVER_TO_VIEW_CALLER",
  SET_DRIVER_TO_VIEW = "SET_DRIVER_TO_VIEW",
}

export enum SearchForDriver {
  GET_SEARCH_FOR_DRIVER_CALLER = "GET_SEARCH_FOR_DRIVER_CALLER",
  GET_SEARCH_FOR_DRIVER_STARTER = "GET_SEARCH_FOR_DRIVER_STARTER",
  GET_SEARCH_FOR_DRIVER_SUCCESS = "GET_SEARCH_FOR_DRIVER_SUCCESS",
  GET_SEARCH_FOR_DRIVER_FAILED = "GET_SEARCH_FOR_DRIVER_FAILED",
  GET_SEARCH_FOR_DRIVER_DEFAULT = "GET_SEARCH_FOR_DRIVER_DEFAULT",
}

export enum GetDriverAnalytics {
  GET__DRIVER_ANALYTICS_CALLER = "GET__DRIVER_ANALYTICS_CALLER",
  GET__DRIVER_ANALYTICS_STARTED = "GET__DRIVER_ANALYTICS_STARTED",
  GET__DRIVER_ANALYTICS_SUCCESS = "GET__DRIVER_ANALYTICS_SUCCESS",
  GET__DRIVER_ANALYTICS_FAILED = "GET__DRIVER_ANALYTICS_FAILED",
  GET__DRIVER_ANALYTICS_DEFAULT = "GET__DRIVER_ANALYTICS_DEFAULT",
}

export enum GetTripInformation {
  GET_TRIP_INFORMATION_CALLER = "GET_TRIP_INFORMATION_CALLER",
  GET_TRIP_INFORMATION_STARTED = "GET_TRIP_INFORMATION_STARTED",
  GET_TRIP_INFORMATION_SUCCESS = "GET_TRIP_INFORMATION_SUCCESS",
  GET_TRIP_INFORMATION_FAILED = "GET_TRIP_INFORMATION_FAILED",
  GET_TRIP_INFORMATION_DEFAULT = "GET_TRIP_INFORMATION_DEFAULT",
}

export enum EnableDriverAccount {
  ENABLE_DRIVER_ACCOUNT_CALLER = "ENABLE_DRIVER_ACCOUNT_CALLER",
  ENABLE_DRIVER_ACCOUNT_STARTED = "ENABLE_DRIVER_ACCOUNT_STARTED",
  ENABLE_DRIVER_ACCOUNT_SUCCESS = "ENABLE_DRIVER_ACCOUNT_SUCCESS",
  ENABLE_DRIVER_ACCOUNT_FAILED = "ENABLE_DRIVER_ACCOUNT_FAILED",
  ENABLE_DRIVER_ACCOUNT_DEFAULT = "ENABLE_DRIVER_ACCOUNT_DEFAULT",
}

export enum DisableDriverAccount {
  DISABLE_DRIVER_ACCOUNT_CALLER = "DISABLE_DRIVER_ACCOUNT_CALLER",
  DISABLE_DRIVER_ACCOUNT_STARTED = "DISABLE_DRIVER_ACCOUNT_STARTED",
  DISABLE_DRIVER_ACCOUNT_SUCCESS = "DISABLE_DRIVER_ACCOUNT_SUCCESS",
  DISABLE_DRIVER_ACCOUNT_FAILED = "DISABLE_DRIVER_ACCOUNT_FAILED",
  DISABLE_DRIVER_ACCOUNT_DEFAULT = "DISABLE_DRIVER_ACCOUNT_DEFAULT",
}

export enum UpdateDriverAccount {
  UPDATE_DRIVER_ACCOUNT_MANAGER_CALLER = "UPDATE_DRIVER_ACCOUNT_MANAGER_CALLER",
  UPDATE_DRIVER_ACCOUNT_MANAGER_STARTED = "UPDATE_DRIVER_ACCOUNT_MANAGER_STARTED",
  UPDATE_DRIVER_ACCOUNT_MANAGER_SUCCESS = "UPDATE_DRIVER_ACCOUNT_MANAGER_SUCCESS",
  UPDATE_DRIVER_ACCOUNT_MANAGER_FAILED = "UPDATE_DRIVER_ACCOUNT_MANAGER_FAILED",
  UPDATE_DRIVER_ACCOUNT_MANAGER_DEFAULT = "UPDATE_DRIVER_ACCOUNT_MANAGER_DEFAULT",
}

export enum AddDriverAccount {
  ADD_DRIVER_ACCOUNT_MANAGER_CALLER = "ADD_DRIVER_ACCOUNT_MANAGER_CALLER",
  ADD_DRIVER_ACCOUNT_MANAGER_STARTED = "ADD_DRIVER_ACCOUNT_MANAGER_STARTED",
  ADD_DRIVER_ACCOUNT_MANAGER_SUCCESS = "ADD_DRIVER_ACCOUNT_MANAGER_SUCCESS",
  ADD_DRIVER_ACCOUNT_MANAGER_FAILED = "ADD_DRIVER_ACCOUNT_MANAGER_FAILED",
  ADD_DRIVER_ACCOUNT_MANAGER_DEFAULT = "ADD_DRIVER_ACCOUNT_MANAGER_DEFAULT",
}

export enum AddSubject {
  ADD_SUBJECTS_MANAGER_CALLER = "ADD_SUBJECTS_MANAGER_CALLER",
  ADD_SUBJECTS_MANAGER_STARTED = "ADD_SUBJECTS_MANAGER_STARTED",
  ADD_SUBJECTS_MANAGER_SUCCESS = "ADD_SUBJECTS_MANAGER_SUCCESS",
  ADD_SUBJECTS_MANAGER_FAILED = "ADD_SUBJECTS_MANAGER_FAILED",
  ADD_SUBJECTS_MANAGER_DEFAULT = "ADD_SUBJECTS_MANAGER_DEFAULT",
}

export enum Subject {
  GET_SUBJECT_CALLER = "GET_SUBJECT_CALLER",
  GET_SUBJECT_STARTER = "GET_SUBJECT_STARTED",
  GET_SUBJECT_SUCCESS = "GET_SUBJECT_SUCCESS",
  GET_SUBJECT_FAILED = "GET_SUBJECT_FAILED",
  GET_SUBJECT_DEFAULT = "GET_SUBJECT_DEFAULT",
}

export enum DeleteSubject {
  DELETE_SUBJECT_CALLER = "DELETE_SUBJECT_CALLER",
  DELETE_SUBJECT_STARTER = "DELETE_SUBJECT_STARTED",
  DELETE_SUBJECT_SUCCESS = "DELETE_SUBJECT_SUCCESS",
  DELETE_SUBJECT_FAILED = "DELETE_SUBJECT_FAILED",
  DELETE_SUBJECT_DEFAULT = "DELETE_SUBJECT_DEFAULT",
}
