export enum Customer {
  GET_CUSTOMER_CALLER = "GET_CUSTOMER_CALLER",
  GET_CUSTOMER_STARTER = "GET_CUSTOMER_STARTER",
  GET_CUSTOMER_SUCCESS = "GET_CUSTOMER_SUCCESS",
  GET_CUSTOMER_FAILURE = "GET_CUSTOMER_FAILURE",
  GET_CUSTOMER_DEFAULT = "GET_CUSTOMER_DEFAULT",
}

export enum ValueSetters {
  //CALLERS
  SET_CUSTOMER_TO_VIEW_CALLER = "SET_CUSTOMER_TO_VIEW_CALLER",

  // SETTERS
  SET_CUSTOMER_TO_VIEW = "SET_CUSTOMER_TO_VIEW",
}

export enum CustomerSearchData {
  GET_CUSTOMER_SEARCH_RESULT_CALLER = "GET_CUSTOMER_SEARCH_RESULT_CALLER",
  GET_CUSTOMER_SEARCH_RESULT_STARTED = "GET_CUSTOMER_SEARCH_RESULT_STARTED",
  GET_CUSTOMER_SEARCH_RESULT_SUCCESS = "GET_CUSTOMER_SEARCH_RESULT_SUCCESS",
  GET_CUSTOMER_SEARCH_RESULT_FAILED = "GET_CUSTOMER_SEARCH_RESULT_FAILED",
  GET_CUSTOMER_SEARCH_RESULT_DEFAULT = "GET_CUSTOMER_SEARCH_RESULT_DEFAULT",
}

export enum GetCustomerAnalytics {
  GET_CUSTOMER_ANALYTICS_CALLER = "GET_CUSTOMER_ANALYTICS_CALLER",
  GET_CUSTOMER_ANALYTICS_STARTED = "GET_CUSTOMER_ANALYTICS_STARTED",
  GET_CUSTOMER_ANALYTICS_SUCCESS = "GET_CUSTOMER_ANALYTICS_SUCCESS",
  GET_CUSTOMER_ANALYTICS_FAILED = "GET_CUSTOMER_ANALYTICS_FAILED",
  GET_CUSTOMER_ANALYTICS_DEFAULT = "GET_CUSTOMER_ANALYTICS_DEFAULT",
}

export enum EnableCustomerAccount {
  ENABLE_CUSTOMER_ACCOUNT_CALLER = "ENABLE_CUSTOMER_ACCOUNT_CALLER",
  ENABLE_CUSTOMER_ACCOUNT_STARTED = "ENABLE_CUSTOMER_ACCOUNT_STARTED",
  ENABLE_CUSTOMER_ACCOUNT_SUCCESS = "ENABLE_CUSTOMER_ACCOUNT_SUCCESS",
  ENABLE_CUSTOMER_ACCOUNT_FAILED = "ENABLE_CUSTOMER_ACCOUNT_FAILED",
  ENABLE_CUSTOMER_ACCOUNT_DEFAULT = "ENABLE_CUSTOMER_ACCOUNT_DEFAULT",
}

export enum DisableCustomerAccount {
  DISABLE_CUSTOMER_ACCOUNT_CALLER = "DISABLE_CUSTOMER_ACCOUNT_CALLER",
  DISABLE_CUSTOMER_ACCOUNT_STARTED = "DISABLE_CUSTOMER_ACCOUNT_STARTED",
  DISABLE_CUSTOMER_ACCOUNT_SUCCESS = "DISABLE_CUSTOMER_ACCOUNT_SUCCESS",
  DISABLE_CUSTOMER_ACCOUNT_FAILED = "DISABLE_CUSTOMER_ACCOUNT_FAILED",
  DISABLE_CUSTOMER_ACCOUNT_DEFAULT = "DISABLE_CUSTOMER_ACCOUNT_DEFAULT",
}

export enum AddAdminAccount {
  ADD_ADMIN_ACCOUNT_CALLER = "ADD_ADMIN_ACCOUNT_CALLER",
  ADD_ADMIN_ACCOUNT_STARTED = "ADD_ADMIN_ACCOUNT_STARTED",
  ADD_ADMIN_ACCOUNT_SUCCESS = "ADD_ADMIN_ACCOUNT_SUCCESS",
  ADD_ADMIN_ACCOUNT_FAILED = "ADD_ADMIN_ACCOUNT_FAILED",
  ADD_ADMIN_ACCOUNT_DEFAULT = "ADD_ADMIN_ACCOUNT_DEFAULT",
}

export enum RemoveAdminAccount {
  REMOVE_ADMIN_ACCOUNT_CALLER = "REMOVE_ADMIN_ACCOUNT_CALLER",
  REMOVE_ADMIN_ACCOUNT_STARTED = "REMOVE_ADMIN_ACCOUNT_STARTED",
  REMOVE_ADMIN_ACCOUNT_SUCCESS = "REMOVE_ADMIN_ACCOUNT_SUCCESS",
  REMOVE_ADMIN_ACCOUNT_FAILED = "REMOVE_ADMIN_ACCOUNT_FAILED",
  REMOVE_ADMIN_ACCOUNT_DEFAULT = "REMOVE_ADMIN_ACCOUNT_DEFAULT",
}

export enum UpdateCustomerAccount {
  UPDATE_CUSTOMER_ACCOUNT_MANAGER_CALLER = "UPDATE_CUSTOMER_ACCOUNT_MANAGER_CALLER",
  UPDATE_CUSTOMER_ACCOUNT_MANAGER_STARTED = "UPDATE_CUSTOMER_ACCOUNT_MANAGER_STARTED",
  UPDATE_CUSTOMER_ACCOUNT_MANAGER_SUCCESS = "UPDATE_CUSTOMER_ACCOUNT_MANAGER_SUCCESS",
  UPDATE_CUSTOMER_ACCOUNT_MANAGER_FAILED = "UPDATE_CUSTOMER_ACCOUNT_MANAGER_FAILED",
  UPDATE_CUSTOMER_ACCOUNT_MANAGER_DEFAULT = "UPDATE__ADMIN_ACCOUNT_MANAGER_DEFAULT",
}

export enum AddCustomerAccount {
  ADD_CUSTOMER_ACCOUNT_MANAGER_CALLER = "ADD_CUSTOMER_ACCOUNT_MANAGER_CALLER",
  ADD_CUSTOMER_ACCOUNT_MANAGER_STARTED = "ADD_CUSTOMER_ACCOUNT_MANAGER_STARTED",
  ADD_CUSTOMER_ACCOUNT_MANAGER_SUCCESS = "ADD_CUSTOMER_ACCOUNT_MANAGER_SUCCESS",
  ADD_CUSTOMER_ACCOUNT_MANAGER_FAILED = "ADD_CUSTOMER_ACCOUNT_MANAGER_FAILED",
  ADD_CUSTOMER_ACCOUNT_MANAGER_DEFAULT = "ADD_CUSTOMER_ACCOUNT_MANAGER_DEFAULT",
}
