export enum DashboardAnalytic {
  GET_DASHBOARD_ANALYTIC_CALLER = "GET_DASHBOARD_ANALYTIC_CALLER",
  GET_DASHBOARD_ANALYTIC_STARTED = "GET_DASHBOARD_ANALYTIC_STARTED",
  GET_DASHBOARD_ANALYTIC_SUCCESS = "GET_DASHBOARD_ANALYTIC_SUCCESS",
  GET_DASHBOARD_ANALYTIC_FAILED = "GET_DASHBOARD_ANALYTIC_FAILED",
  GET_DASHBOARD_ANALYTIC_DEFAULT = "GET_DASHBOARD_ANALYTIC_DEFAULT",
}

export enum GetTripsByStatus {
  GET_TRIPS_BY_STATUS_CALLER = "GET_TRIPS_BY_STATUS_CALLER",
  GET_TRIPS_BY_STATUS_STARTED = "GET_TRIPS_BY_STATUS_STARTED",
  GET_TRIPS_BY_STATUS_SUCCESS = "GET_TRIPS_BY_STATUS_SUCCESS",
  GET_TRIPS_BY_STATUS_FAILED = "GET_TRIPS_BY_STATUS_FAILED",
  GET_TRIPS_BY_STATUS_DEFAULT = "GET_TRIPS_BY_STATUS_DEFAULT",
}
